site_name: MUSWAH
theme:
  name: material
  palette: 
    scheme: slate
nav:
    - Home: index.md
    - Get Involved: get-involved.md
    - Contributors: contributors.md
extra_css:
  - stylesheets/extra.css
